# Site settings
course_name: Informatica per le biotecnologie
course_description: "Introduzione all'algoritmica e alla programmazione"
course_semester: "Primo semestre 2025"

baseurl: "/btcl/" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

schoolname: "University of Pisa"
schoolurl: "https://www.biologia.unipi.it/"

address: |
    Largo B. Pontecorvo, 3, Pisa

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
